// The registry scan: what the Vite plugin runs at `configResolved` and what
// `pnpm gen` runs before tsc or vitest start. It reads
// `src/extensions/*/manifest.json`, checks what it can see on disk, and emits
// `src/registry.gen.ts` and `src/registry.server.gen.ts` importing every
// present entrypoint. The merge itself, with its collision errors, is
// `src/registry.ts`. Plain JavaScript so node runs it without a build. BO_0202_001
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export class RegistryScanError extends Error {
  /** @param {string} code @param {string} message */
  constructor(code, message) {
    super(message);
    this.name = "RegistryScanError";
    this.code = code;
  }
}

const CLIENT_SHAPE = /export\s+const\s+contributions\b/u;
const SERVER_SHAPE = /export\s+const\s+contributions\b/u;

/**
 * Every extension directory under `src/extensions/`, in name order, with the
 * halves of its entrypoint that exist. Throws a named error for a directory
 * without a manifest, an id not matching its directory, an entrypoint that
 * resolves to no module, a half that does not export `contributions`, and a
 * declared dependency the tree does not hold.
 * @param {string} root
 * @returns {{ id: string, dir: string, manifest: Record<string, unknown>, client: string | null, server: string | null }[]}
 */
export function scanExtensions(root) {
  const base = join(root, "src", "extensions");
  const entries = [];
  const names = existsSync(base) ? readdirSync(base).sort() : [];
  for (const name of names) {
    const dir = join(base, name);
    if (!statSync(dir).isDirectory()) continue;
    const manifestPath = join(dir, "manifest.json");
    if (!existsSync(manifestPath)) {
      throw new RegistryScanError("manifest_missing", `src/extensions/${name} has no manifest.json`);
    }
    /** @type {Record<string, unknown>} */
    let manifest;
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    } catch (error) {
      throw new RegistryScanError("manifest_unreadable", `src/extensions/${name}/manifest.json: ${String(error)}`);
    }
    if (manifest.id !== name) {
      throw new RegistryScanError(
        "id_mismatch",
        `src/extensions/${name}/manifest.json declares id ${JSON.stringify(manifest.id)}`,
      );
    }
    let client = null;
    let server = null;
    if (manifest.entrypoint !== undefined) {
      if (typeof manifest.entrypoint !== "string" || manifest.entrypoint === "" || manifest.entrypoint.includes("/")) {
        throw new RegistryScanError("entrypoint_shape", `${name}: entrypoint must be a module name beside the manifest`);
      }
      const stem = join(dir, manifest.entrypoint);
      client = [".ts", ".tsx"].map((ext) => stem + ext).find((file) => existsSync(file)) ?? null;
      server = existsSync(`${stem}.server.ts`) ? `${stem}.server.ts` : null;
      if (client === null && server === null) {
        throw new RegistryScanError(
          "entrypoint_missing",
          `${name}: entrypoint ${manifest.entrypoint} names neither ${manifest.entrypoint}.ts nor ${manifest.entrypoint}.server.ts`,
        );
      }
      if (client !== null && !CLIENT_SHAPE.test(readFileSync(client, "utf8"))) {
        throw new RegistryScanError("entrypoint_shape", `${name}: ${relativeTo(root, client)} does not export \`contributions\``);
      }
      if (server !== null && !SERVER_SHAPE.test(readFileSync(server, "utf8"))) {
        throw new RegistryScanError("entrypoint_shape", `${name}: ${relativeTo(root, server)} does not export \`contributions\``);
      }
    }
    entries.push({ id: name, dir, manifest, client, server });
  }
  const present = new Set(entries.map((entry) => entry.id));
  for (const entry of entries) {
    const dependencies = entry.manifest.dependencies;
    if (typeof dependencies !== "object" || dependencies === null) continue;
    for (const dependency of Object.keys(dependencies)) {
      if (!present.has(dependency)) {
        throw new RegistryScanError(
          "dependency_missing",
          `${entry.id} depends on ${dependency}, which the tree does not hold`,
        );
      }
    }
  }
  return entries;
}

/** @param {string} root @param {string} file */
function relativeTo(root, file) {
  return file.startsWith(root) ? file.slice(root.length).replace(/^[\\/]/u, "") : file;
}

const HEADER =
  "// Generated by scripts/registry.mjs from src/extensions/*/manifest.json.\n" +
  "// A *.gen.* module: the kernel never commits it and every build regenerates it. BO_0202_001\n";

/** @param {ReturnType<typeof scanExtensions>} entries */
export function emitClient(entries) {
  const withClient = entries.filter((entry) => entry.client !== null);
  const lines = [
    HEADER,
    'import { buildRegistry } from "~/registry";',
    'import { HOST_CONTRIBUTIONS } from "~/components/shell/host-contributions";',
    ...withClient.map(
      (entry, index) => `import { contributions as ext${index} } from "~/extensions/${entry.id}/${moduleName(entry.client)}";`,
    ),
    "",
    `export const PRESENT_EXTENSIONS: readonly string[] = ${JSON.stringify(entries.map((entry) => entry.id))};`,
    "",
    "export const REGISTRY = buildRegistry(HOST_CONTRIBUTIONS, [",
    ...withClient.map((entry, index) => `  { id: ${JSON.stringify(entry.id)}, contributions: ext${index} },`),
    "]);",
    "",
  ];
  return lines.join("\n");
}

/** @param {ReturnType<typeof scanExtensions>} entries */
export function emitServer(entries) {
  const withServer = entries.filter((entry) => entry.server !== null);
  const lines = [
    HEADER,
    'import { buildServerRegistry } from "~/registry";',
    ...withServer.map(
      (entry, index) => `import { contributions as ext${index} } from "~/extensions/${entry.id}/${moduleName(entry.server)}";`,
    ),
    "",
    `export const PRESENT_EXTENSIONS: readonly string[] = ${JSON.stringify(entries.map((entry) => entry.id))};`,
    "",
    "export const SERVER_REGISTRY = buildServerRegistry([",
    ...withServer.map((entry, index) => `  { id: ${JSON.stringify(entry.id)}, contributions: ext${index} },`),
    "]);",
    "",
  ];
  return lines.join("\n");
}

/** @param {string | null} file */
function moduleName(file) {
  return (file ?? "").split(/[\\/]/u).pop()?.replace(/\.tsx?$/u, "") ?? "";
}

/**
 * Scans and writes both generated modules under `src/`, touching a file only
 * when its text changed so a watcher does not loop on its own output.
 * @param {string} root
 */
export function writeRegistry(root) {
  const entries = scanExtensions(root);
  const written = [];
  for (const [file, text] of [
    [join(root, "src", "registry.gen.ts"), emitClient(entries)],
    [join(root, "src", "registry.server.gen.ts"), emitServer(entries)],
  ]) {
    const current = existsSync(file) ? readFileSync(file, "utf8") : null;
    if (current !== text) {
      writeFileSync(file, text);
      written.push(file);
    }
  }
  return { entries, written };
}
